# Prob3.5.5

$$
B_n = \begin{bmatrix}
1 & -1 & -1 & \ldots & -1 \\
0 & 1 & -1 & \ldots & -1 \\
0 & 0 & 1 & \ldots & -1 \\
\vdots & \vdots & \vdots & \ddots & -1 \\
0 & 0 & 0 & \ldots & 1
\end{bmatrix}
$$

$$
B_4 = \begin{bmatrix}
1 & -1 & -1 & -1 \\
0 & 1 & -1 & -1 \\
0 & 0 & 1 & -1 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

estimate the condition number of $B_n$


In [33]:
import numpy as np

# maximize y in U@y=d 
def condition_estimator_upper(U):
    n = len(U)
    p = np.zeros(n)
    y = np.zeros(n)
    d = np.zeros(n)
    
    for k in reversed(range(n)):
        y_p = (1 - p[k]) / U[k, k]
        y_m = (-1 - p[k]) / U[k, k]    
        if k > 0:
            p_p = p[:k] + U[:k, k] * y_p
            p_m = p[:k] + U[:k, k] * y_m
            s1 = abs(y_p) + np.linalg.norm(p_p, ord=1)
            s2 = abs(y_m) + np.linalg.norm(p_m, ord=1)
        else:
            s1 = abs(y_p)
            s2 = abs(y_m)
        if s1 >= s2:
            y[k] = y_p
            d[k] = 1
            if k > 0:
                p[:k] = p_p
        else:
            y[k] = y_m
            d[k] = -1
            if k > 0:
                p[:k] = p_m
    
    cond_num = np.linalg.norm(y, ord=np.inf) * np.linalg.norm(U, ord=np.inf)
    return cond_num, y, d

def create_Bn(n):
    B = np.eye(n)
    B[np.triu_indices(n, k=1)] = -1
    return B

n = 4
B = create_Bn(n)
cond_num, y, d = condition_estimator_upper(B)
print("*********************************************")
print(f"n={n}")
print("\nBn:")
print(B)
print("\ny:")
print(y)
print("\nBn@y: ")
print(B @ y)
print("\nd:")
print(d)
print("\ncondition number estimation:", cond_num)


*********************************************
n=4

Bn:
[[ 1. -1. -1. -1.]
 [ 0.  1. -1. -1.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]

y:
[8. 4. 2. 1.]

Bn@y: 
[1. 1. 1. 1.]

d:
[1. 1. 1. 1.]

condition number estimation: 32.0


In [32]:
B_inv = np.linalg.inv(B)
true_cond_num = np.linalg.norm(B_inv, ord=np.inf) * np.linalg.norm(B, ord=np.inf)
print("\nBn:")
print(B)
print("\ninv(Bn)")
print(B_inv)
print(f"\nTrue condition number of B{n}:", true_cond_num) # 32


Bn:
[[ 1. -1. -1. -1.]
 [ 0.  1. -1. -1.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]

inv(Bn)
[[1. 1. 2. 4.]
 [0. 1. 1. 2.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]

True condition number of B4: 32.0


In [34]:
for n in range(2, 10):
    B = create_Bn(n)
    B_inv = np.linalg.inv(B)
    cond_num, y, d = condition_estimator_upper(B)
    print("*********************************************")
    print(f"n={n}")
    print("\nBn:")
    print(B)
    print("\ninv(Bn)")
    print(B_inv)
    print("\ny:")
    print(y)
    print("\nBn@y: ")
    print(B @ y)
    print("\nd:")
    print(d)
    print("\ncondition number estimation:", cond_num)


*********************************************
n=2

Bn:
[[ 1. -1.]
 [ 0.  1.]]

inv(Bn)
[[1. 1.]
 [0. 1.]]

y:
[2. 1.]

Bn@y: 
[1. 1.]

d:
[1. 1.]

condition number estimation: 4.0
*********************************************
n=3

Bn:
[[ 1. -1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  1.]]

inv(Bn)
[[1. 1. 2.]
 [0. 1. 1.]
 [0. 0. 1.]]

y:
[4. 2. 1.]

Bn@y: 
[1. 1. 1.]

d:
[1. 1. 1.]

condition number estimation: 12.0
*********************************************
n=4

Bn:
[[ 1. -1. -1. -1.]
 [ 0.  1. -1. -1.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]

inv(Bn)
[[1. 1. 2. 4.]
 [0. 1. 1. 2.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]

y:
[8. 4. 2. 1.]

Bn@y: 
[1. 1. 1. 1.]

d:
[1. 1. 1. 1.]

condition number estimation: 32.0
*********************************************
n=5

Bn:
[[ 1. -1. -1. -1. -1.]
 [ 0.  1. -1. -1. -1.]
 [ 0.  0.  1. -1. -1.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  1.]]

inv(Bn)
[[1. 1. 2. 4. 8.]
 [0. 1. 1. 2. 4.]
 [0. 0. 1. 1. 2.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]

y:
[16.  8.  4.  2.  1